name: cs_training_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.1.0
  flutter_typeahead: ^5.2.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.1.5
  intl: ^0.19.0
  table_calendar: ^3.0.9
  fl_chart: ^0.66.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleToFill
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

